export const getEnvVariables = () => {
  const { VITE_API_URL, VITE_GOOGLE_API_KEY } = import.meta.env;
  const { VITE_CLOUDINARY_URL, VITE_CLIENT_AUTH0, VITE_DOMAIN_AUTH0, VITE_AUDIENCE_AUTH0 } = import.meta.env;

  return { VITE_API_URL, VITE_GOOGLE_API_KEY, VITE_CLOUDINARY_URL, VITE_CLIENT_AUTH0, VITE_DOMAIN_AUTH0, VITE_AUDIENCE_AUTH0 };
};
